# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BlinkBox_v12_BottomStatus.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1225, 458)
        self.objectOptionsTabWidth = QtGui.QTabWidget(Form)
        self.objectOptionsTabWidth.setGeometry(QtCore.QRect(10, 0, 1311, 451))
        self.objectOptionsTabWidth.setTabsClosable(False)
        self.objectOptionsTabWidth.setMovable(True)
        self.objectOptionsTabWidth.setObjectName(_fromUtf8("objectOptionsTabWidth"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.widget = QtGui.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(0, 1, 1181, 261))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.cancelButton = QtGui.QPushButton(self.widget)
        self.cancelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelButton.setObjectName(_fromUtf8("cancelButton"))
        self.gridLayout.addWidget(self.cancelButton, 10, 3, 1, 1)
        self.okayButton = QtGui.QPushButton(self.widget)
        self.okayButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.okayButton.setObjectName(_fromUtf8("okayButton"))
        self.gridLayout.addWidget(self.okayButton, 10, 2, 1, 1)
        self.zoomHorizontalSlider = QtGui.QSlider(self.widget)
        self.zoomHorizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zoomHorizontalSlider.setObjectName(_fromUtf8("zoomHorizontalSlider"))
        self.gridLayout.addWidget(self.zoomHorizontalSlider, 9, 1, 1, 3)
        self.strokeWidthSpinBox = QtGui.QSpinBox(self.widget)
        self.strokeWidthSpinBox.setObjectName(_fromUtf8("strokeWidthSpinBox"))
        self.gridLayout.addWidget(self.strokeWidthSpinBox, 1, 3, 1, 1)
        self.radiusLabel = QtGui.QLabel(self.widget)
        self.radiusLabel.setObjectName(_fromUtf8("radiusLabel"))
        self.gridLayout.addWidget(self.radiusLabel, 3, 0, 1, 1)
        self.widthLabel = QtGui.QLabel(self.widget)
        self.widthLabel.setObjectName(_fromUtf8("widthLabel"))
        self.gridLayout.addWidget(self.widthLabel, 1, 0, 1, 1)
        self.StrokeTypeLabel = QtGui.QLabel(self.widget)
        self.StrokeTypeLabel.setObjectName(_fromUtf8("StrokeTypeLabel"))
        self.gridLayout.addWidget(self.StrokeTypeLabel, 2, 2, 1, 1)
        self.xPositionLabel = QtGui.QLabel(self.widget)
        self.xPositionLabel.setObjectName(_fromUtf8("xPositionLabel"))
        self.gridLayout.addWidget(self.xPositionLabel, 3, 2, 1, 1)
        self.xPositionSpinBox = QtGui.QSpinBox(self.widget)
        self.xPositionSpinBox.setObjectName(_fromUtf8("xPositionSpinBox"))
        self.gridLayout.addWidget(self.xPositionSpinBox, 3, 3, 1, 1)
        self.yPositionSpinBox = QtGui.QSpinBox(self.widget)
        self.yPositionSpinBox.setObjectName(_fromUtf8("yPositionSpinBox"))
        self.gridLayout.addWidget(self.yPositionSpinBox, 4, 3, 1, 1)
        self.strokeTypeComboBox = QtGui.QComboBox(self.widget)
        self.strokeTypeComboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.strokeTypeComboBox.setObjectName(_fromUtf8("strokeTypeComboBox"))
        self.gridLayout.addWidget(self.strokeTypeComboBox, 2, 3, 1, 1)
        self.yPositionLabel = QtGui.QLabel(self.widget)
        self.yPositionLabel.setObjectName(_fromUtf8("yPositionLabel"))
        self.gridLayout.addWidget(self.yPositionLabel, 4, 2, 1, 1)
        self.strokeWidthLabel = QtGui.QLabel(self.widget)
        self.strokeWidthLabel.setObjectName(_fromUtf8("strokeWidthLabel"))
        self.gridLayout.addWidget(self.strokeWidthLabel, 1, 2, 1, 1)
        self.lengthEntry = QtGui.QLineEdit(self.widget)
        self.lengthEntry.setMaxLength(50000)
        self.lengthEntry.setObjectName(_fromUtf8("lengthEntry"))
        self.gridLayout.addWidget(self.lengthEntry, 4, 1, 1, 1)
        self.widthEntry = QtGui.QLineEdit(self.widget)
        self.widthEntry.setMaxLength(50000)
        self.widthEntry.setObjectName(_fromUtf8("widthEntry"))
        self.gridLayout.addWidget(self.widthEntry, 1, 1, 1, 1)
        self.heightLabel = QtGui.QLabel(self.widget)
        self.heightLabel.setObjectName(_fromUtf8("heightLabel"))
        self.gridLayout.addWidget(self.heightLabel, 2, 0, 1, 1)
        self.zoomLabel = QtGui.QLabel(self.widget)
        self.zoomLabel.setObjectName(_fromUtf8("zoomLabel"))
        self.gridLayout.addWidget(self.zoomLabel, 9, 0, 1, 1)
        self.heightEntry = QtGui.QLineEdit(self.widget)
        self.heightEntry.setMaxLength(50000)
        self.heightEntry.setObjectName(_fromUtf8("heightEntry"))
        self.gridLayout.addWidget(self.heightEntry, 2, 1, 1, 1)
        self.lengthLabel = QtGui.QLabel(self.widget)
        self.lengthLabel.setObjectName(_fromUtf8("lengthLabel"))
        self.gridLayout.addWidget(self.lengthLabel, 4, 0, 1, 1)
        self.raduisEntry = QtGui.QLineEdit(self.widget)
        self.raduisEntry.setMaxLength(50000)
        self.raduisEntry.setObjectName(_fromUtf8("raduisEntry"))
        self.gridLayout.addWidget(self.raduisEntry, 3, 1, 1, 1)
        self.selectStrokeColorButton = QtGui.QPushButton(self.widget)
        self.selectStrokeColorButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.selectStrokeColorButton.setObjectName(_fromUtf8("selectStrokeColorButton"))
        self.gridLayout.addWidget(self.selectStrokeColorButton, 1, 4, 1, 1)
        self.selectFillColorButton = QtGui.QPushButton(self.widget)
        self.selectFillColorButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.selectFillColorButton.setObjectName(_fromUtf8("selectFillColorButton"))
        self.gridLayout.addWidget(self.selectFillColorButton, 3, 4, 1, 1)
        self.objectOptionsTabWidth.addTab(self.tab, _fromUtf8(""))
        self.serialTab = QtGui.QWidget()
        self.serialTab.setObjectName(_fromUtf8("serialTab"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.serialTab)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 1, 1171, 282))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.sendButton = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.sendButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.sendButton.setObjectName(_fromUtf8("sendButton"))
        self.verticalLayout_2.addWidget(self.sendButton)
        self.readAllButton = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.readAllButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.readAllButton.setObjectName(_fromUtf8("readAllButton"))
        self.verticalLayout_2.addWidget(self.readAllButton)
        self.save2FileButton = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.save2FileButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save2FileButton.setObjectName(_fromUtf8("save2FileButton"))
        self.verticalLayout_2.addWidget(self.save2FileButton)
        self.clearButton = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.clearButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.clearButton.setObjectName(_fromUtf8("clearButton"))
        self.verticalLayout_2.addWidget(self.clearButton)
        self.connectButton = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.connectButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.connectButton.setObjectName(_fromUtf8("connectButton"))
        self.verticalLayout_2.addWidget(self.connectButton)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.serialMessageEntry = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.serialMessageEntry.setMaxLength(200000)
        self.serialMessageEntry.setObjectName(_fromUtf8("serialMessageEntry"))
        self.verticalLayout_3.addWidget(self.serialMessageEntry)
        self.serialMessageDisplay = QtGui.QPlainTextEdit(self.gridLayoutWidget_2)
        self.serialMessageDisplay.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.serialMessageDisplay.setFrameShadow(QtGui.QFrame.Plain)
        self.serialMessageDisplay.setReadOnly(True)
        self.serialMessageDisplay.setObjectName(_fromUtf8("serialMessageDisplay"))
        self.verticalLayout_3.addWidget(self.serialMessageDisplay)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.serialPortEntry = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.serialPortEntry.setMaxLength(200000)
        self.serialPortEntry.setObjectName(_fromUtf8("serialPortEntry"))
        self.gridLayout_2.addWidget(self.serialPortEntry, 1, 1, 1, 1)
        self.baudrateEntry = QtGui.QLineEdit(self.gridLayoutWidget_2)
        self.baudrateEntry.setMaxLength(200000)
        self.baudrateEntry.setObjectName(_fromUtf8("baudrateEntry"))
        self.gridLayout_2.addWidget(self.baudrateEntry, 2, 1, 1, 1)
        self.serialPortLabel = QtGui.QLabel(self.gridLayoutWidget_2)
        self.serialPortLabel.setObjectName(_fromUtf8("serialPortLabel"))
        self.gridLayout_2.addWidget(self.serialPortLabel, 1, 0, 1, 1)
        self.baudrateLabel = QtGui.QLabel(self.gridLayoutWidget_2)
        self.baudrateLabel.setObjectName(_fromUtf8("baudrateLabel"))
        self.gridLayout_2.addWidget(self.baudrateLabel, 2, 0, 1, 1)
        self.objectOptionsTabWidth.addTab(self.serialTab, _fromUtf8(""))

        self.retranslateUi(Form)
        self.objectOptionsTabWidth.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Form", None))
        self.cancelButton.setText(_translate("Form", "Cancel", None))
        self.okayButton.setText(_translate("Form", "Okay", None))
        self.radiusLabel.setText(_translate("Form", "Radius", None))
        self.widthLabel.setText(_translate("Form", "Width", None))
        self.StrokeTypeLabel.setText(_translate("Form", "Stroke Type", None))
        self.xPositionLabel.setText(_translate("Form", "xPosition", None))
        self.yPositionLabel.setText(_translate("Form", "yPositon", None))
        self.strokeWidthLabel.setText(_translate("Form", "Stroke Width", None))
        self.heightLabel.setText(_translate("Form", "Height", None))
        self.zoomLabel.setText(_translate("Form", "Zoom", None))
        self.lengthLabel.setText(_translate("Form", "Length", None))
        self.selectStrokeColorButton.setText(_translate("Form", "Select Stroke Color", None))
        self.selectFillColorButton.setText(_translate("Form", "Select Fill Color", None))
        self.objectOptionsTabWidth.setTabText(self.objectOptionsTabWidth.indexOf(self.tab), _translate("Form", "Object Properties", None))
        self.sendButton.setText(_translate("Form", "Send", None))
        self.readAllButton.setText(_translate("Form", "Read All", None))
        self.save2FileButton.setText(_translate("Form", "Save to File", None))
        self.clearButton.setText(_translate("Form", "Clear", None))
        self.connectButton.setText(_translate("Form", "Connect", None))
        self.serialPortLabel.setText(_translate("Form", "Serial Port", None))
        self.baudrateLabel.setText(_translate("Form", "Baud Rate", None))
        self.objectOptionsTabWidth.setTabText(self.objectOptionsTabWidth.indexOf(self.serialTab), _translate("Form", "Bluetooth Com port settings", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Form = QtGui.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

